GP tutorial NumPy error
The `Gaussian_Process_Gpytorch` tutorial has been updated for conversion
to MDX. See #1392 for more info about the updates. Only minor edits were
made including:

- link updates
- markdown display of dataframes
- using ArviZ for summary statistics
- spelling and grammar checks

In cells 12 and 13, we attempt to show the summary statistics from ArviZ
for the model. The following error occurs when converting the Bean
Machine `MonteCarloSamples` object to either an xarray or ArviZ
`InferenceData` object.

```python
RuntimeError: Can't call numpy() on Tensor that requires grad. Use
tensor.detach().numpy() instead.
```

This error is coming from the `to_inference_data` method, and can be
seen in the stack trace in the notebook.