GP tutorial NumPy error (#1399)
Summary:
The `Gaussian_Process_Gpytorch` tutorial has been updated for conversion
to MDX. See https://github.com/facebookresearch/beanmachine/issues/1392 for more info about the updates. Only minor edits were
made including:

- link updates
- markdown display of dataframes
- using ArviZ for summary statistics
- spelling and grammar checks

In cells 12 and 13, we attempt to show the summary statistics from ArviZ
for the model. The following error occurs when converting the Bean
Machine `MonteCarloSamples` object to either an xarray or ArviZ
`InferenceData` object.

```python
RuntimeError: Can't call numpy() on Tensor that requires grad. Use
tensor.detach().numpy() instead.
```

This error is coming from the `to_inference_data` method, and can be
seen in the stack trace in the notebook.

### Types of changes
- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/facebookresearch/beanmachine/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

Pull Request resolved: https://github.com/facebookresearch/beanmachine/pull/1399

Test Plan:
Imported from GitHub, without a `Test Plan:` line.

**Static Docs Preview: beanmachine**
|[Full Site](https://our.intern.facebook.com/intern/staticdocs/eph/D35437628/V6/beanmachine/)|

|**Modified Pages**|
|[docs/hamiltonian_monte_carlo](https://our.intern.facebook.com/intern/staticdocs/eph/D35437628/V6/beanmachine/docs/hamiltonian_monte_carlo/)|
|[docs/block_inference](https://our.intern.facebook.com/intern/staticdocs/eph/D35437628/V6/beanmachine/docs/block_inference/)|
|[docs/no_u_turn_sampler](https://our.intern.facebook.com/intern/staticdocs/eph/D35437628/V6/beanmachine/docs/no_u_turn_sampler/)|
|[docs/overview/analysis](https://our.intern.facebook.com/intern/staticdocs/eph/D35437628/V6/beanmachine/docs/overview/analysis/)|

Reviewed By: feynmanliang

Differential Revision: D35437628

Pulled By: horizon-blue

fbshipit-source-id: 2d6d9f207b28d23bc359fa7c53f1363656a7140d