BMGInference error
In cell 24 of the Neal's funnel tutorial, we get an error from
BMGInference that states

```python
TypeError: loop of ufunc does not support argument 0 of type
ExpNode which has no callable log method
```

The tutorial has been updated so it integrates with the converter from
ipynb to mdx for the website. Only minor edits were made, including:

- running `black` on the notebook
- spelling and grammar updates
- `<div>` styling for mdx conversion
- markdown displays of dataframes
- using ArviZ for summary statistics
- KaTeX adjustments

See PR #1392